//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThreeHShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string NOIDUNGTT { get; set; }
        public Nullable<decimal> GIACA { get; set; }
        public string HINHMINHHOA { get; set; }
        public int MALSP { get; set; }
        public int MADM { get; set; }
    
        public virtual CHITIETKHUYENMAI CHITIETKHUYENMAI { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
